version: '3.9'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/app_db
      REDIS_URL: redis://redis:6379
      PORT: 3000
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
    command: sh -c "npx prisma migrate deploy && npm run start"

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata:
